### ISSUE TITLE
遠端 DB 連線失敗，cors 問題

### ISSUE THREAD

**Issue by chachachater** [outshaker/foodmap-backend#36]
在 github page 測試連線遠端 DB，，之前測試連線正常，今天測試發現被擋了。

不太確定問題在哪，目前懷疑是主機的 cors 問題，請問主機的** `env.ALLOWED_ORIGIN` 目前是寫入甚麼?
![image](https://user-images.githubusercontent.com/71329979/136942612-ebcc2727-51c4-4749-9d7f-f03aaa1da73d.png)
![image](https://user-images.githubusercontent.com/71329979/136942667-63c266d2-7739-4692-b4f9-03ebc1a69655.png)

**Comment by outshaker** [comment]
已修復，目前 'http://localhost:3000', 'https://chachachater.github.io' 應該都可以正確呼叫
